version: "3.3"

services:
  web:
    image: ghcr.io/mingj7235/summonerswar_strategy_app/main:latest
    container_name: summonerswar
    environment:
      TZ: "Asia/Seoul"
    networks:
      - bridge
    env_file:
      - summonerswar.env
    ports:
      - "8080:8080"
    depends_on:
      - web-server
#      - redis

  web-server:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - bridge
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    command: [ nginx-debug, '-g', 'daemon off;' ]

#  redis:
#    image: redis:6.2.5-alpine
#    container_name: redis
#    networks:
#      - bridge
#    environment:
#      TZ: "Asia/Seoul"
#    volumes:
#      - redis:/data
#    restart: always
#    ports:
#      - "6379:6379"

volumes:
#  redis:
  web-server:

networks:
  bridge:
    driver: bridge