name: Summoners CI / CD

on:
  push:
    branches:
      - prd

env:
  REGISTRY_NAME: ghcr.io
  GITHUB_USER_NAME: ${{ secrets.USER_NAME }}
  DOCKER_FILE_PATH: ./Dockerfile
  DOCKER_COMPOSE: docker-compose.yml
  IMAGE_NAME: ghcr.io/${{ github.repository }}/main
  PROJECT_NAME: summonerswar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set Gradle Permission
        run: chmod +x ./gradlew

      - name: Gradle Build
        run: ./gradlew clean bootJar -x test

      - name: Set up Docker Buildx for Caching
        uses: docker/setup-buildx-action@v1

    #################### GITHUB CONTAINER REGISTRY LOGIN ########################

      - name: Login to Github Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ env.GITHUB_USER_NAME }}
          password: ${{ secrets.ACCOUNT_TOKEN }}

    #################### DOCKER BUILD AND PUSH ###############################

      - name: Build Push Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: ${{ env.DOCKER_FILE_PATH }}
          tags: ${{ env.IMAGE_NAME }}:latest
#          no-cache: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true

    ######################## DEPLOY ################################

  deploy:
    name: Summnerswar CD with Docker
    needs: build
    runs-on: self-hosted

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ env.GITHUB_USER_NAME }}
          password: ${{ secrets.ACCOUNT_TOKEN }}

      - name: Docker Run Run
        run: |
          docker-compose -f ${{ env.DOCKER_COMPOSE }} pull 
          docker-compose -f ${{ env.DOCKER_COMPOSE }} --project-name=${{ env.PROJECT_NAME }} up -d
          docker image prune -f
          docker network prune -f